// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/v1/legacy_authz.proto

package authzv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LegacyAuthzService_LegacyGetUserPermissions_FullMethodName = "/authz.v1.LegacyAuthzService/LegacyGetUserPermissions"
)

// LegacyAuthzServiceClient is the client API for LegacyAuthzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LegacyAuthzServiceClient interface {
	// No HTTP route is exposed.
	LegacyGetUserPermissions(ctx context.Context, in *LegacyGetUserPermissionsRequest, opts ...grpc.CallOption) (LegacyAuthzService_LegacyGetUserPermissionsClient, error)
}

type legacyAuthzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLegacyAuthzServiceClient(cc grpc.ClientConnInterface) LegacyAuthzServiceClient {
	return &legacyAuthzServiceClient{cc}
}

func (c *legacyAuthzServiceClient) LegacyGetUserPermissions(ctx context.Context, in *LegacyGetUserPermissionsRequest, opts ...grpc.CallOption) (LegacyAuthzService_LegacyGetUserPermissionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LegacyAuthzService_ServiceDesc.Streams[0], LegacyAuthzService_LegacyGetUserPermissions_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &legacyAuthzServiceLegacyGetUserPermissionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LegacyAuthzService_LegacyGetUserPermissionsClient interface {
	Recv() (*LegacyGetUserPermissionsResponse, error)
	grpc.ClientStream
}

type legacyAuthzServiceLegacyGetUserPermissionsClient struct {
	grpc.ClientStream
}

func (x *legacyAuthzServiceLegacyGetUserPermissionsClient) Recv() (*LegacyGetUserPermissionsResponse, error) {
	m := new(LegacyGetUserPermissionsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LegacyAuthzServiceServer is the server API for LegacyAuthzService service.
// All implementations must embed UnimplementedLegacyAuthzServiceServer
// for forward compatibility
type LegacyAuthzServiceServer interface {
	// No HTTP route is exposed.
	LegacyGetUserPermissions(*LegacyGetUserPermissionsRequest, LegacyAuthzService_LegacyGetUserPermissionsServer) error
	mustEmbedUnimplementedLegacyAuthzServiceServer()
}

// UnimplementedLegacyAuthzServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLegacyAuthzServiceServer struct {
}

func (UnimplementedLegacyAuthzServiceServer) LegacyGetUserPermissions(*LegacyGetUserPermissionsRequest, LegacyAuthzService_LegacyGetUserPermissionsServer) error {
	return status.Errorf(codes.Unimplemented, "method LegacyGetUserPermissions not implemented")
}
func (UnimplementedLegacyAuthzServiceServer) mustEmbedUnimplementedLegacyAuthzServiceServer() {}

// UnsafeLegacyAuthzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LegacyAuthzServiceServer will
// result in compilation errors.
type UnsafeLegacyAuthzServiceServer interface {
	mustEmbedUnimplementedLegacyAuthzServiceServer()
}

func RegisterLegacyAuthzServiceServer(s grpc.ServiceRegistrar, srv LegacyAuthzServiceServer) {
	s.RegisterService(&LegacyAuthzService_ServiceDesc, srv)
}

func _LegacyAuthzService_LegacyGetUserPermissions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LegacyGetUserPermissionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LegacyAuthzServiceServer).LegacyGetUserPermissions(m, &legacyAuthzServiceLegacyGetUserPermissionsServer{stream})
}

type LegacyAuthzService_LegacyGetUserPermissionsServer interface {
	Send(*LegacyGetUserPermissionsResponse) error
	grpc.ServerStream
}

type legacyAuthzServiceLegacyGetUserPermissionsServer struct {
	grpc.ServerStream
}

func (x *legacyAuthzServiceLegacyGetUserPermissionsServer) Send(m *LegacyGetUserPermissionsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LegacyAuthzService_ServiceDesc is the grpc.ServiceDesc for LegacyAuthzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LegacyAuthzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authz.v1.LegacyAuthzService",
	HandlerType: (*LegacyAuthzServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LegacyGetUserPermissions",
			Handler:       _LegacyAuthzService_LegacyGetUserPermissions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/legacy_authz.proto",
}
